apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: neurallog-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: redis.neurallog.local  # Replace with your domain
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: neurallog-server-redis
            port:
              number: 80
  - host: nedb.neurallog.local  # Replace with your domain
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: neurallog-server-nedb
            port:
              number: 80
  - host: memory.neurallog.local  # Replace with your domain
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: neurallog-server-memory
            port:
              number: 80
