apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap.yaml
  - secret.yaml
  - redis-deployment.yaml
  - server-redis-deployment.yaml
  - server-nedb-deployment.yaml
  - server-memory-deployment.yaml
  - ingress.yaml
